'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Pedidos', [
  {
    cliente_id: 1,
    endereco_cliente_id: 1,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 2,
    endereco_cliente_id: 2,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 3,
    endereco_cliente_id: 3,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 4,
    endereco_cliente_id: 4,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 5,
    endereco_cliente_id: 5,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 6,
    endereco_cliente_id: 6,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 7,
    endereco_cliente_id: 7,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 8,
    endereco_cliente_id: 8,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 9,
    endereco_cliente_id: 9,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    cliente_id: 10,
    endereco_cliente_id: 10,
    valor_total_pedido: 120,
    data_entrega: '2022-09-25',
    data_pedido: '2022-09-01',
    valor_frete: 10,
    cupom_desconto: false,
    status_pedido: "Em análise",
    createdAt: new Date(),
    updatedAt: new Date(),
  },


], {});
},
  async down (queryInterface, Sequelize) {

    await queryInterface.bulkDelete('Pedidos', null, {});

  }
};